import { useEffect, useRef, useState, type FormEvent } from "react";
import EnergyGlobe from "../components/EnergyGlobe";
import { FaTelegram } from 'react-icons/fa';
import {
  Zap,
  Sun,
  BatteryCharging,
  BrainCircuit,
  Plug,
  Sparkles,
  PiggyBank,
  Send,
  Mail,
  Linkedin,
  Github,
  Facebook,
  ArrowRight,
  PlayCircle,
  ShieldCheck,
  Leaf,
  TrendingUp,
  Check,
  Cpu,
  Globe,
  Activity,
  Menu,
  X
} from "lucide-react";
import { toast } from "sonner";
import i18n from "../i18n";
import { animate, createScope, createTimeline, stagger, utils } from "animejs";

const azCopy: Record<string, string> = {
  "Features": "Xüsusiyyətlər",
  "Analytics": "Statistika",
  "How It Works": "Necə işləyir",
  "Contact": "Əlaqə",
  "Smart Solar Integration": "Ağıllı günəş inteqrasiyası",
  "AI analyzes your solar production in real time using advanced weather forecasting algorithms.": "Süni intellekt hava proqnozu alqoritmləri ilə günəş enerjisi istehsalınızı real vaxtda analiz edir.",
  "Dynamic Battery Balancing": "Dinamik batareya balansı",
  "Automatically switch to battery power during peak tariff hours and keep your energy costs under control.": "Yüksək tarif saatlarında avtomatik olaraq batareya enerjisinə keçin və xərclərinizi nəzarətdə saxlayın.",
  "Neural Consumption Analysis": "Neyron istehlak analizi",
  "Your daily energy habits are learned by neural networks so waste can be detected and reduced.": "Gündəlik enerji vərdişləriniz neyron şəbəkələr tərəfindən öyrənilir və israf azalır.",
  "Connect in Seconds": "Saniyələr ərzində qoşulun",
  "Connect digitally to your existing inverter and smart meter without additional hardware changes.": "Əlavə avadanlıq dəyişikliyi olmadan mövcud invertor və ağıllı sayğacınıza rəqəmsal qoşulun.",
  "AI-Powered Analysis": "Süni intellekt analizi",
  "The system maps your energy profile, detects anomalies, and creates a strategy for your home.": "Sistem enerji profilinizi yaradır, anomaliyaları aşkarlayır və eviniz üçün strategiya hazırlayır.",
  "Automated Savings": "Avtomatlaşdırılmış qənaət",
  "EcoAI makes smart decisions for you and can reduce monthly energy costs by up to 40%.": "EcoAI sizin üçün ağıllı qərarlar verir və aylıq enerji xərclərini 40%-ə qədər azalda bilər.",
  "Solar Production": "Günəş enerjisi istehsalı",
  "Total monthly production": "Aylıq ümumi istehsal",
  "Smart Savings": "Ağıllı qənaət",
  "Savings from tariff optimization": "Tarif optimallaşdırmasından qənaət",
  "CO₂ Reduced": "Azaldılmış CO₂",
  "Carbon prevented from entering the atmosphere": "Atmosferə buraxılmasının qarşısı alınan karbon",
  "Grid Dependency": "Şəbəkədən asılılıq",
  "Dependence on the public grid": "İctimai şəbəkədən asılılıq",
  "Product": "Məhsul",
  "Dashboard": "İdarə paneli",
  "AI Optimizer": "AI optimallaşdırıcı",
  "Grid Control": "Şəbəkə idarəsi",
  "Company": "Şirkət",
  "About Us": "Haqqımızda",
  "Team": "Komanda",
  "Careers": "Karyera",
  "Resources": "Resurslar",
  "Documentation": "Sənədlər",
  "Blog": "Bloq",
  "Support": "Dəstək",
  "Legal": "Hüquqi",
  "Privacy": "Məxfilik",
  "Terms of Service": "İstifadə şərtləri",
  "Log in": "Daxil ol",
  "Get started": "Başlayın",
  "Start": "Başla",
  "Open menu": "Menyunu aç",
  "Close menu": "Menyunu bağla",
  "POWERFUL CAPABILITIES": "GÜCLÜ FUNKSİONALLIQ",
  "What Does EcoAI Do?": "EcoAI nə edir?",
  "Distribute your energy intelligently with fully automated control.": "Tam avtomatlaşdırılmış idarəetmə ilə enerjinizi ağıllı şəkildə bölüşdürün.",
  "LIVE METRICS": "CANLI GÖSTƏRİCİLƏR",
  "Measurable": "Ölçülə bilən",
  "Results": "nəticələr",
  "Your real-time savings balance, powered by artificial intelligence.": "Süni intellekt tərəfindən idarə olunan real vaxt qənaət balansınız.",
  "Annual Analytics Report": "İllik analitika hesabatı",
  "Real-time energy distribution for each month (kWh)": "Hər ay üçün real vaxt enerji paylanması (kWh)",
  "Energy Production": "Enerji istehsalı",
  "Generated by panels": "Panellər tərəfindən yaradılıb",
  "Energy Consumption": "Enerji istehlakı",
  "Consumed by devices": "Cihazlar tərəfindən istifadə olunub",
  "SIMPLE AND FAST": "SADƏ VƏ SÜRƏTLİ",
  "Connect in Just 3 Steps": "Cəmi 3 addımda qoşulun",
  "FREE ENERGY AUDIT": "PULSUZ ENERJİ AUDİTİ",
  "Experience the Future of Energy Today": "Enerjinin gələcəyini bu gün yaşayın",
  "Start today and we will prepare a free savings simulation tailored to your home's current tariffs.": "Bu gün başlayın, evinizin mövcud tariflərinə uyğun pulsuz qənaət simulyasiyası hazırlayaq.",
  "14-day commitment-free trial": "14 günlük öhdəliksiz sınaq",
  "Live ROI report": "Canlı ROI hesabatı",
  "Ad Soyad": "Ad Soyad",
  "Your full name": "Adınızı və soyadınızı daxil edin",
  "Phone number": "Telefon nömrəsi",
  "Sending...": "Göndərilir...",
  "Please enter your name and email": "Zəhmət olmasa adınızı və e-poçtunuzu daxil edin",
  "Your request has been received": "Müraciətiniz qəbul edildi",
  "Our team will contact you shortly.": "Komandamız tezliklə sizinlə əlaqə saxlayacaq.",
  "Something went wrong. Please try again.": "Xəta baş verdi, yenidən cəhd edin",
  "Made with ⚡ in Baku": "⚡ ilə Bakıda hazırlanıb",
  "All rights reserved.": "Bütün hüquqlar qorunur.",
  "Battery": "Batareya",
  "Solar": "Günəş",
  "Total Production": "Ümumi istehsal",
  "Efficiency": "Effektivlik",
  "Home Consumption": "Ev istehlakı",
  "NEURAL CORE": "NEYRON MƏRKƏZ",
  "ACTIVE": "AKTİV",
  "Build the Future of Energy": "Enerjinin gələcəyini qurun",
  "with AI": "süni intellektlə",
  "Automate complex energy flows. EcoAI integrates your home into a smarter grid, using artificial intelligence to reduce costs and minimize your carbon footprint.": "Mürəkkəb enerji axınlarını avtomatlaşdırın. EcoAI evinizi ağıllı şəbəkəyə inteqrasiya edir, xərcləri və karbon izinizi azaldır.",
  "Try the Platform": "Platformanı sınayın",
  "See How It Works": "Necə işlədiyini görün",
  "An AI-powered platform for green energy optimization.": "Süni intellekt əsaslı yaşıl enerji optimallaşdırma platforması.",
  "E-mail": "E-poçt",
};

// --- STRUCTURAL DATA & TYPES ---
interface NavItem {
  label: string;
  href: string;
}

interface FeatureItem {
  icon: React.ComponentType<{ className?: string }>;
  title: string;
  desc: string;
  tag: string;
  glow: string;
}

interface StepItem {
  n: string;
  icon: React.ComponentType<{ className?: string }>;
  title: string;
  desc: string;
}

interface FooterCol {
  title: string;
  links: string[];
}

interface StatItem {
  label: string;
  value: string;
  desc: string;
  pct: string;
  pctUp: boolean;
  color: string;
  glow: string;
  icon: React.ComponentType<{ className?: string }>;
}

const nav: NavItem[] = [
  { label: "Features", href: "#features" },
  { label: "Analytics", href: "#stats" },
  { label: "How It Works", href: "#how" },
  { label: "Contact", href: "#contact" },
];

const features: FeatureItem[] = [
  {
    icon: Sun,
    title: "Smart Solar Integration",
    desc: "AI analyzes your solar production in real time using advanced weather forecasting algorithms.",
    tag: "SOLAR AI",
    glow: "rgba(234, 179, 8, 0.15)"
  },
  {
    icon: BatteryCharging,
    title: "Dynamic Battery Balancing",
    desc: "Automatically switch to battery power during peak tariff hours and keep your energy costs under control.",
    tag: "SMART GRID",
    glow: "rgba(16, 185, 129, 0.15)"
  },
  {
    icon: BrainCircuit,
    title: "Neural Consumption Analysis",
    desc: "Your daily energy habits are learned by neural networks so waste can be detected and reduced.",
    tag: "NEURAL OPT",
    glow: "rgba(6, 182, 212, 0.15)"
  },
];

const steps: StepItem[] = [
  { n: "01", icon: Plug, title: "Connect in Seconds", desc: "Connect digitally to your existing inverter and smart meter without additional hardware changes." },
  { n: "02", icon: Sparkles, title: "AI-Powered Analysis", desc: "The system maps your energy profile, detects anomalies, and creates a strategy for your home." },
  { n: "03", icon: PiggyBank, title: "Automated Savings", desc: "EcoAI makes smart decisions for you and can reduce monthly energy costs by up to 40%." },
];

const statsData: StatItem[] = [
  { label: "Solar Production", value: "720 kWh", desc: "Total monthly production", pct: "+14.8%", pctUp: true, color: "#fbbf24", glow: "rgba(250,204,21,0.2)", icon: Sun },
  { label: "Smart Savings", value: "₼184.50", desc: "Savings from tariff optimization", pct: "+28.2%", pctUp: true, color: "#10b981", glow: "rgba(16,185,129,0.2)", icon: PiggyBank },
  { label: "CO₂ Reduced", value: "1.2 Ton", desc: "Carbon prevented from entering the atmosphere", pct: "-18.5%", pctUp: true, color: "#64ffda", glow: "rgba(100,255,218,0.2)", icon: Leaf },
  { label: "Grid Dependency", value: "14.2%", desc: "Dependence on the public grid", pct: "-45.0%", pctUp: false, color: "#ef4444", glow: "rgba(239,68,68,0.2)", icon: Zap }
];

const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

const chartData = {
  production: [42, 58, 51, 67, 73, 81, 88, 84, 76, 69, 78, 92],
  consumption: [68, 62, 58, 45, 40, 32, 28, 35, 41, 52, 60, 71]
};

const footerCols: FooterCol[] = [
  { title: "Product", links: ["Dashboard", "Analytics", "AI Optimizer", "Grid Control"] },
  { title: "Company", links: ["About Us", "Team", "Careers", "Press"] },
  { title: "Resources", links: ["Documentation", "API", "Blog", "Support"] },
  { title: "Legal", links: ["Privacy", "Terms of Service", "Cookies", "GDPR"] },
];

function SplitChars({ text, charClass = "" }: { text: string; charClass?: string }) {
  return (
    <>
      {text.split("").map((ch: string, i: number) =>
        ch === " " ? (
          <span key={i} className="inline-block">&nbsp;</span>
        ) : (
          <span key={i} className={`hero-char inline-block ${charClass}`}>{ch}</span>
        )
      )}
    </>
  );
}

function CountUp({ value, duration = 1800 }: { value: string; duration?: number }) {
  const ref = useRef<HTMLSpanElement>(null);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const match = value.match(/-?\d[\d.]*/);
    if (!match) return;
    const target = parseFloat(match[0]);
    const decimals = (match[0].split(".")[1] || "").length;
    const counter = { n: 0 };
    let anim: any = null;
    el.textContent = value.replace(match[0], (0).toFixed(decimals));
    const io = new IntersectionObserver((entries) => {
      if (entries.some((e) => e.isIntersecting)) {
        anim = animate(counter, {
          n: target,
          duration,
          ease: "out(4)",
          onUpdate: () => { el.textContent = value.replace(match[0], counter.n.toFixed(decimals)); },
        });
        io.disconnect();
      }
    }, { threshold: 0.6 });
    io.observe(el);
    return () => { io.disconnect(); anim?.pause(); };
  }, [value, duration]);
  return <span ref={ref}>{value}</span>;
}

function Logo() {
  return (
    <a href="#" className="flex items-center gap-2 group">
      <span className="relative grid place-items-center w-9 h-9 rounded-xl backdrop-blur-md bg-white/10 border border-white/10">
        <Zap className="w-5 h-5 text-[#64ffda] drop-shadow-[0_0_8px_rgba(100,255,218,0.7)]" strokeWidth={2.5} />
      </span>
      <span className="text-lg font-semibold tracking-tight">
        Eco<span className="text-[#64ffda]">AI</span>
      </span>
    </a>
  );
}

function Interactive3DGrid() {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const mouseRef = useRef({ x: 0, y: 0, targetX: 0, targetY: 0 });
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;
    let animationFrameId: number;
    let width = (canvas.width = window.innerWidth);
    let height = (canvas.height = window.innerHeight);
    const particles: any[] = [];
    const count = 120;
    for (let i = 0; i < count; i++) {
      const theta = Math.random() * Math.PI * 2;
      const phi = Math.acos(Math.random() * 2 - 1);
      const r = 250 + Math.random() * 100;
      particles.push({
        x: r * Math.sin(phi) * Math.cos(theta),
        y: r * Math.sin(phi) * Math.sin(theta),
        z: r * Math.cos(phi),
      });
    }
    const handleMouseMove = (e: MouseEvent) => {
      mouseRef.current.targetX = (e.clientX - width / 2) * 0.0015;
      mouseRef.current.targetY = (e.clientY - height / 2) * 0.0015;
    };
    const handleResize = () => {
      width = canvas.width = window.innerWidth;
      height = canvas.height = window.innerHeight;
    };
    window.addEventListener("mousemove", handleMouseMove);
    window.addEventListener("resize", handleResize);
    const rotate = (p: any, angleX: number, angleY: number) => {
      const cosX = Math.cos(angleX);
      const sinX = Math.sin(angleX);
      const y1 = p.y * cosX - p.z * sinX;
      const z1 = p.y * sinX + p.z * cosX;
      const cosY = Math.cos(angleY);
      const sinY = Math.sin(angleY);
      const x2 = p.x * cosY + z1 * sinY;
      const z2 = -p.x * sinY + z1 * cosY;
      return { x: x2, y: y1, z: z2 };
    };
    let angleX = 0;
    let angleY = 0;
    const render = () => {
      ctx.clearRect(0, 0, width, height);
      mouseRef.current.x += (mouseRef.current.targetX - mouseRef.current.x) * 0.05;
      mouseRef.current.y += (mouseRef.current.targetY - mouseRef.current.y) * 0.05;
      angleX = mouseRef.current.y + 0.002;
      angleY = mouseRef.current.x + 0.003;
      const projected: any[] = [];
      particles.forEach((p) => {
        const rotated = rotate(p, angleX, angleY);
        p.x = rotated.x; p.y = rotated.y; p.z = rotated.z;
        const fov = 400; const distance = 600;
        const scale = fov / (fov + p.z + distance);
        projected.push({ x: p.x * scale + width / 2, y: p.y * scale + height / 2, depth: p.z });
      });
      ctx.lineWidth = 0.5;
      for (let i = 0; i < projected.length; i++) {
        for (let j = i + 1; j < projected.length; j++) {
          const dist = Math.hypot(projected[i].x - projected[j].x, projected[i].y - projected[j].y);
          if (dist < 90) {
            ctx.strokeStyle = `rgba(100, 255, 218, ${(1 - dist / 90) * 0.15})`;
            ctx.beginPath(); ctx.moveTo(projected[i].x, projected[i].y); ctx.lineTo(projected[j].x, projected[j].y); ctx.stroke();
          }
        }
      }
      projected.forEach((p) => {
        ctx.fillStyle = `rgba(100, 255, 218, ${Math.max(0.1, (200 - p.depth) * 0.004)})`;
        ctx.beginPath(); ctx.arc(p.x, p.y, Math.max(1, (200 - p.depth) * 0.015), 0, Math.PI * 2); ctx.fill();
      });
      animationFrameId = requestAnimationFrame(render);
    };
    render();
    return () => { cancelAnimationFrame(animationFrameId); window.removeEventListener("mousemove", handleMouseMove); window.removeEventListener("resize", handleResize); };
  }, []);
  return <canvas ref={canvasRef} className="pointer-events-none fixed inset-0 -z-10 block opacity-40" />;
}

function TiltCard({ children, className = "", intensity = 10, style = {} }: any) {
  const cardRef = useRef<HTMLDivElement>(null);
  const [rotateX, setRotateX] = useState(0);
  const [rotateY, setRotateY] = useState(0);
  const handleMouseMove = (e: any) => {
    if (!cardRef.current) return;
    const rect = cardRef.current.getBoundingClientRect();
    setRotateY(((e.clientX - rect.left - rect.width / 2) / (rect.width / 2)) * intensity);
    setRotateX(-((e.clientY - rect.top - rect.height / 2) / (rect.height / 2)) * intensity);
  };
  return (
    <div ref={cardRef} onMouseMove={handleMouseMove} onMouseLeave={() => { setRotateX(0); setRotateY(0); }} className={`transition-all duration-300 ease-out ${className}`} style={{ ...style, transform: `perspective(1000px) rotateX(${rotateX}deg) rotateY(${rotateY}deg)`, transformStyle: "preserve-3d" }}>
      {children}
    </div>
  );
}

export default function LandingPage() {
  const [form, setForm] = useState({ name: "", email: "", phone: "" });
  const [loading, setLoading] = useState(false);
  const [activeTab, setActiveTab] = useState<"production" | "consumption">("production");
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [language, setLanguage] = useState<"en" | "az">(i18n.language === "az" ? "az" : "en");

  const switchLanguage = (nextLanguage: "en" | "az") => {
    setLanguage(nextLanguage);
    void i18n.changeLanguage(nextLanguage);
    localStorage.setItem("ecoai_lang", nextLanguage);
  };

  const tx = (value: string) => language === "az" ? (azCopy[value] ?? value) : value;
  const localizedNav = nav.map((item) => ({ ...item, label: tx(item.label) }));
  const localizedFeatures = features.map((item) => ({ ...item, title: tx(item.title), desc: tx(item.desc) }));
  const localizedSteps = steps.map((item) => ({ ...item, title: tx(item.title), desc: tx(item.desc) }));
  const localizedStats = statsData.map((item) => ({ ...item, label: tx(item.label), desc: tx(item.desc) }));
  const localizedFooter = footerCols.map((column) => ({ ...column, title: tx(column.title), links: column.links.map(tx) }));

  const rootRef = useRef<HTMLDivElement>(null);
  const chartRef = useRef<HTMLDivElement>(null);
  const closeMobileMenu = () => setMobileMenuOpen(false);

  useEffect(() => {
    const scope = createScope({ root: rootRef }).add(() => {
      utils.set([".hero-nav", ".hero-badge", ".hero-char", ".hero-shimmer", ".hero-sub", ".hero-cta", ".hero-trust", ".hero-card"], { opacity: 0 });
      createTimeline({ defaults: { ease: "out(3)", duration: 800 } })
        .add(".hero-nav", { opacity: [0, 1], translateY: [-24, 0], duration: 700 })
        .add(".hero-badge", { opacity: [0, 1], translateY: [24, 0] }, "-=450")
        .add(".hero-char", { opacity: [0, 1], translateY: [70, 0], delay: stagger(26) }, "-=500")
        .add(".hero-shimmer", { opacity: [0, 1], translateY: [50, 0] }, "-=600")
        .add(".hero-sub", { opacity: [0, 1], translateY: [24, 0] }, "-=550")
        .add(".hero-cta", { opacity: [0, 1], translateY: [24, 0], delay: stagger(120), duration: 650 }, "-=500")
        .add(".hero-trust", { opacity: [0, 1], duration: 600 }, "-=400")
        .add(".hero-card", { opacity: [0, 1], scale: [0.92, 1], duration: 1100 }, "-=1000");
      animate(".hero-card", { translateY: [0, -10], alternate: true, loop: true, duration: 3000, ease: "inOutSine", delay: 2400 });
    });
    return () => scope.revert();
  }, []);

  useEffect(() => {
    const root = rootRef.current;
    if (!root) return;
    const groups = Array.from(root.querySelectorAll<HTMLElement>(".reveal-group"));
    const observers: IntersectionObserver[] = [];
    groups.forEach((group) => {
      const items = Array.from(group.querySelectorAll<HTMLElement>(".reveal-item"));
      const targets = items.length ? items : [group];
      utils.set(targets, { opacity: 0, translateY: 48 });
      const io = new IntersectionObserver((entries) => {
        if (entries.some((e) => e.isIntersecting)) {
          animate(targets, { opacity: 1, translateY: 0, delay: stagger(110), duration: 850, ease: "out(3)" });
          io.disconnect();
        }
      }, { threshold: 0.15 });
      io.observe(group);
      observers.push(io);
    });
    return () => observers.forEach((o) => o.disconnect());
  }, []);

  useEffect(() => {
    const bars = chartRef.current?.querySelectorAll(".chart-bar");
    if (!bars || bars.length === 0) return;
    const anim = animate(bars, { scaleY: [0, 1], opacity: [0.4, 1], delay: stagger(45), duration: 750, ease: "out(3)" });
    return () => {
      anim.pause();
    };
  }, [activeTab]);

  const onSubmit = async (e: FormEvent) => {
    e.preventDefault();
    if (!form.name || !form.email) {
      toast.error(tx("Please enter your name and email"));
      return;
    }
    setLoading(true);
    try {
      const { createClient } = await import('@supabase/supabase-js');
      const supabase = createClient(import.meta.env.VITE_SUPABASE_URL, import.meta.env.VITE_SUPABASE_ANON_KEY);
      await supabase.from('muracietler').insert({ tam_ad: form.name, email: form.email, mobil: form.phone || null, oxunub: false });
      toast.success(tx("Your request has been received"), { description: tx("Our team will contact you shortly.") });
      setForm({ name: "", email: "", phone: "" });
    } catch {
      toast.error(tx("Something went wrong. Please try again."));
    } finally {
      setLoading(false);
    }
  };

  return (
    <div ref={rootRef} className="relative min-h-[100dvh] bg-[#030d0a] text-white selection:bg-[#64ffda]/30 selection:text-white overflow-hidden">
      <Interactive3DGrid />
      <div className="pointer-events-none fixed inset-0 -z-10">
        <div className="absolute top-[-10%] left-[-10%] w-[50vw] h-[50vw] rounded-full bg-[rgba(100,255,218,0.03)] blur-[120px]" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[50vw] h-[50vw] rounded-full bg-[rgba(16,185,129,0.03)] blur-[120px]" />
      </div>

      <header className="fixed top-0 inset-x-0 z-50 px-4 sm:px-6 pt-4 sm:pt-6">
        <nav className="hero-nav mx-auto max-w-7xl backdrop-blur-xl bg-black/20 border border-white/5 rounded-2xl px-4 sm:px-6 py-3 sm:py-4 flex items-center justify-between">
          <Logo />
          <ul className="hidden md:flex items-center gap-10 text-sm font-medium text-gray-400">
            {localizedNav.map((n: NavItem) => (
              <li key={n.href}>
                <a href={n.href} className="hover:text-[#64ffda] transition-colors duration-300">{n.label}</a>
              </li>
            ))}
          </ul>
          <div className="flex items-center gap-2 sm:gap-4">
            <div className="hidden sm:flex items-center rounded-lg border border-white/10 bg-white/5 p-1 text-[11px] font-bold tracking-wider" aria-label="Language selector">
              <button type="button" onClick={() => switchLanguage("en")} className={`rounded-md px-2 py-1 transition ${language === "en" ? "bg-[#64ffda] text-[#030d0a]" : "text-gray-400 hover:text-white"}`}>EN</button>
              <button type="button" onClick={() => switchLanguage("az")} className={`rounded-md px-2 py-1 transition ${language === "az" ? "bg-[#64ffda] text-[#030d0a]" : "text-gray-400 hover:text-white"}`}>AZ</button>
            </div>
            <a href="/login" className="hidden sm:inline-flex text-sm text-gray-300 hover:text-white font-medium transition">
              {tx("Log in")}
            </a>
            <a href="#contact" className="relative group overflow-hidden px-3 sm:px-5 py-2 sm:py-2.5 rounded-xl text-xs sm:text-sm font-semibold bg-[#00e699]/10 border border-[#00e699]/30 text-[#00e699] hover:text-white transition-all duration-300">
              <span className="absolute inset-0 bg-[#00e699] translate-y-full group-hover:translate-y-0 transition-transform duration-300 -z-10" />
              <span className="hidden sm:inline">{tx("Get started")}</span>
              <span className="sm:hidden">{tx("Start")}</span>
            </a>
            <button onClick={() => setMobileMenuOpen(true)} className="md:hidden w-9 h-9 flex items-center justify-center rounded-lg bg-white/5 border border-white/10 text-white hover:bg-white/10 transition" aria-label={tx("Open menu")}>
              <Menu className="w-5 h-5" />
            </button>
          </div>
        </nav>
      </header>

      <div className={`fixed inset-0 z-[60] md:hidden transition-opacity duration-200 ${mobileMenuOpen ? 'opacity-100 pointer-events-auto' : 'opacity-0 pointer-events-none'}`}>
        <div onClick={closeMobileMenu} className="absolute inset-0 bg-black/70 backdrop-blur-sm" />
        <div className={`absolute right-0 top-0 h-full w-[280px] max-w-[85vw] bg-[#030d0a]/95 backdrop-blur-xl border-l border-white/10 shadow-2xl flex flex-col transition-transform duration-200 ease-out ${mobileMenuOpen ? 'translate-x-0' : 'translate-x-full'}`}>
          <div className="flex items-center justify-between p-4 border-b border-white/10">
            <Logo />
            <button onClick={closeMobileMenu} className="w-9 h-9 flex items-center justify-center rounded-lg bg-white/5 border border-white/10 text-white hover:bg-white/10 transition" aria-label={tx("Close menu")}>
              <X className="w-5 h-5" />
            </button>
          </div>
          <nav className="flex-1 overflow-y-auto p-4 space-y-1">
            {localizedNav.map((n: NavItem) => (
              <a key={n.href} href={n.href} onClick={closeMobileMenu} className="block px-4 py-3 rounded-xl text-sm font-medium text-gray-300 hover:text-white hover:bg-white/5 transition">{n.label}</a>
            ))}
            <div className="pt-4 mt-4 border-t border-white/10 space-y-2">
              <a href="/login" onClick={closeMobileMenu} className="block px-4 py-3 rounded-xl text-sm font-semibold text-white bg-white/5 border border-white/10 hover:bg-white/10 transition text-center">{tx("Log in")}</a>
              <a href="#contact" onClick={closeMobileMenu} className="block px-4 py-3 rounded-xl text-sm font-semibold bg-[#00e699]/10 border border-[#00e699]/30 text-[#00e699] hover:bg-[#00e699]/20 transition text-center">{tx("Get started")}</a>
            </div>
          </nav>
        </div>
      </div>

      <section className="relative pt-28 sm:pt-36 lg:pt-44 pb-20 sm:pb-28 lg:pb-32 px-4 sm:px-6 min-h-[100dvh] flex items-center overflow-hidden">
        <div className="absolute inset-0 -z-0 opacity-50 pointer-events-none"><EnergyGlobe /></div>
        <div className="mx-auto w-full max-w-7xl grid lg:grid-cols-12 gap-10 lg:gap-16 items-center relative z-10">
          <div className="lg:col-span-6 space-y-6 sm:space-y-8">
            <div className="hero-badge inline-flex items-center gap-2 px-4 py-2 rounded-full border border-[#64ffda]/20 bg-[#64ffda]/5 text-xs font-semibold tracking-wider text-[#64ffda]">
              <Cpu className="w-3.5 h-3.5" /> ECO-ENERGY REVOLUTION · BETA V2.4
            </div>
            <h1 className="text-4xl sm:text-6xl md:text-7xl font-bold tracking-tight leading-[1.05]">
              <SplitChars text={tx("Build the Future of Energy")} charClass="bg-gradient-to-b from-white via-white to-gray-500 bg-clip-text text-transparent" />
              <br />
              <span className="hero-shimmer inline-block text-shimmer bg-gradient-to-r from-[#64ffda] via-[#00e699] to-[#64ffda]">{tx("with AI")}</span>
            </h1>
            <p className="hero-sub text-base sm:text-lg text-gray-400 max-w-xl leading-relaxed">
              {tx("Automate complex energy flows. EcoAI integrates your home into a smarter grid, using artificial intelligence to reduce costs and minimize your carbon footprint.")}
            </p>
            <div className="flex flex-col sm:flex-row flex-wrap gap-3 sm:gap-4 pt-4">
              <a href="#contact" className="hero-cta inline-flex items-center justify-center gap-2.5 px-6 sm:px-8 py-3.5 sm:py-4 rounded-xl bg-[#00e699] text-[#030d0a] font-bold hover:bg-[#00cc88] shadow-[0_0_30px_rgba(0,230,153,0.3)] hover:shadow-[0_0_40px_rgba(0,230,153,0.5)] transition-all duration-300">
                {tx("Try the Platform")} <ArrowRight className="w-5 h-5" />
              </a>
              <a href="#how" className="hero-cta inline-flex items-center justify-center gap-2.5 px-6 sm:px-8 py-3.5 sm:py-4 rounded-xl backdrop-blur-md bg-white/5 border border-white/10 text-white font-semibold hover:bg-white/10 transition-all">
                <PlayCircle className="w-5 h-5 text-[#64ffda]" /> {tx("See How It Works")}
              </a>
            </div>
            <div className="hero-trust flex flex-wrap items-center gap-8 pt-6 text-xs text-gray-500 font-medium">
              <div className="flex items-center gap-2"><ShieldCheck className="w-4 h-4 text-[#64ffda]" /> GDPR-READY SYSTEM</div>
              <div className="flex items-center gap-2"><Globe className="w-4 h-4 text-[#64ffda]" /> LIVE CLOUD CONTROL</div>
            </div>
          </div>
          <div className="lg:col-span-6 flex justify-center relative mt-2 lg:mt-0">
            <div className="hero-card relative z-10 w-full max-w-[500px]">
              <TiltCard intensity={15} className="w-full rounded-[32px] border border-[#64ffda]/30 bg-[#030d0a]/60 p-5 sm:p-8 shadow-[0_0_50px_rgba(100,255,218,0.1)] backdrop-blur-xl flex flex-col gap-6 sm:gap-8" style={{ transformStyle: "preserve-3d" }}>
                <div className="flex justify-between items-center gap-3" style={{ transform: "translateZ(40px)" }}>
                  <div className="flex items-center gap-3">
                    <div className="relative flex h-3 w-3">
                      <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-[#00e699] opacity-75"></span>
                      <span className="relative inline-flex rounded-full h-3 w-3 bg-[#00e699]"></span>
                    </div>
                    <span className="text-xs sm:text-sm font-bold tracking-widest text-white">{tx("NEURAL CORE")}</span>
                  </div>
                  <div className="px-3 py-1.5 rounded-lg bg-[#64ffda]/10 border border-[#64ffda]/30 text-[#64ffda] text-[10px] font-bold tracking-widest">{tx("ACTIVE")}</div>
                </div>
                <div className="relative h-44 sm:h-56 rounded-2xl border border-white/10 bg-black/40 overflow-hidden flex items-center justify-center shadow-inner" style={{ transform: "translateZ(80px)" }}>
                  <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,rgba(100,255,218,0.15)_0%,transparent_70%)]"></div>
                  <div className="w-full flex items-center justify-between px-3 sm:px-8 relative z-10">
                    <div className="flex flex-col items-center gap-2">
                      <div className="w-10 h-10 sm:w-14 sm:h-14 rounded-full border border-yellow-500/40 bg-yellow-500/10 flex items-center justify-center shadow-[0_0_20px_rgba(234,179,8,0.2)]"><Sun className="w-5 h-5 sm:w-7 sm:h-7 text-yellow-400" /></div>
                      <span className="text-[10px] sm:text-xs font-medium text-gray-400 uppercase tracking-wider">{tx("Solar")}</span>
                    </div>
                    <div className="flex-1 h-px bg-gradient-to-r from-yellow-500/30 via-[#64ffda]/30 to-[#64ffda]/30 mx-2 sm:mx-4 relative"><div className="absolute top-1/2 -translate-y-1/2 w-1.5 h-1.5 rounded-full bg-yellow-300 shadow-[0_0_8px_yellow]" style={{ animation: 'slideRight 2s linear infinite' }}></div></div>
                    <div className="flex flex-col items-center gap-2"><div className="relative w-16 h-16 sm:w-20 sm:h-20 rounded-full border-2 border-[#64ffda] bg-[#64ffda]/10 flex items-center justify-center shadow-[0_0_40px_rgba(100,255,218,0.4)] backdrop-blur-md"><BrainCircuit className="w-8 h-8 sm:w-10 sm:h-10 text-[#64ffda] animate-pulse" /><div className="absolute inset-0 rounded-full border border-[#64ffda] animate-ping opacity-20" style={{ animationDuration: '3s' }}></div></div></div>
                    <div className="flex-1 h-px bg-gradient-to-l from-emerald-500/30 via-[#64ffda]/30 to-[#64ffda]/30 mx-2 sm:mx-4 relative"><div className="absolute top-1/2 -translate-y-1/2 w-1.5 h-1.5 rounded-full bg-emerald-300 shadow-[0_0_8px_#34d399]" style={{ animation: 'slideLeft 2.5s linear infinite' }}></div></div>
                    <div className="flex flex-col items-center gap-2">
                      <div className="w-10 h-10 sm:w-14 sm:h-14 rounded-full border border-emerald-500/40 bg-emerald-500/10 flex items-center justify-center shadow-[0_0_20px_rgba(16,185,129,0.2)]"><BatteryCharging className="w-5 h-5 sm:w-7 sm:h-7 text-emerald-400" /></div>
                      <span className="text-[10px] sm:text-xs font-medium text-gray-400 uppercase tracking-wider">{tx("Battery")}</span>
                    </div>
                  </div>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 sm:gap-4" style={{ transform: "translateZ(60px)" }}>
                  <div className="p-3 sm:p-4 rounded-xl bg-white/5 border border-white/5 flex flex-col justify-center">
                    <span className="text-[9px] sm:text-[10px] text-gray-400 block mb-1 tracking-wider uppercase">{tx("Total Production")}</span>
                    <span className="text-sm sm:text-lg font-bold text-white">4.2 kW</span>
                  </div>
                  <div className="p-3 sm:p-4 rounded-xl bg-[#64ffda]/10 border border-[#64ffda]/20 flex flex-col justify-center items-center text-center shadow-[0_0_20px_rgba(100,255,218,0.1)]">
                    <span className="text-[9px] sm:text-[10px] text-[#64ffda] block mb-1 tracking-wider uppercase">{tx("Efficiency")}</span>
                    <span className="text-sm sm:text-lg font-extrabold text-[#64ffda]">+38%</span>
                  </div>
                  <div className="p-3 sm:p-4 rounded-xl bg-white/5 border border-white/5 flex flex-col justify-center text-right">
                    <span className="text-[9px] sm:text-[10px] text-gray-400 block mb-1 tracking-wider uppercase">{tx("Home Consumption")}</span>
                    <span className="text-sm sm:text-lg font-bold text-white">1.8 kW</span>
                  </div>
                </div>
              </TiltCard>
            </div>
          </div>
        </div>
      </section>

      <section id="features" className="relative py-32 px-6 border-t border-white/5">
        <div className="mx-auto max-w-7xl reveal-group">
          <div className="reveal-item text-center max-w-2xl mx-auto mb-20 space-y-4">
            <span className="text-[#64ffda] text-xs font-bold tracking-[0.3em] uppercase">{tx("POWERFUL CAPABILITIES")}</span>
            <h2 className="text-4xl md:text-5xl font-bold tracking-tight">{tx("What Does EcoAI Do?")}</h2>
            <p className="text-gray-400">{tx("Distribute your energy intelligently with fully automated control.")}</p>
          </div>
          <div className="grid md:grid-cols-3 gap-8">
            {localizedFeatures.map((f: any, i: number) => (
              <TiltCard key={i} intensity={8} className="reveal-item relative group rounded-3xl border border-white/5 bg-gradient-to-b from-white/5 to-transparent p-8 hover:border-[#64ffda]/20 transition-all duration-500" style={{ transformStyle: "preserve-3d" }}>
                <div className="absolute inset-0 rounded-3xl pointer-events-none opacity-0 group-hover:opacity-100 transition-all duration-500" style={{ background: f.glow, filter: "blur(40px)", transform: "translateZ(-10px)" }} />
                <div className="w-12 h-12 rounded-2xl bg-[#64ffda]/10 border border-[#64ffda]/20 flex items-center justify-center text-[#64ffda] mb-8" style={{ transform: "translateZ(40px)" }}><f.icon className="w-6 h-6" /></div>
                <div className="space-y-3" style={{ transform: "translateZ(60px)" }}>
                  <span className="text-[10px] font-bold text-[#64ffda] tracking-widest">{f.tag}</span>
                  <h3 className="text-2xl font-bold text-white">{f.title}</h3>
                  <p className="text-sm text-gray-400 leading-relaxed">{f.desc}</p>
                </div>
              </TiltCard>
            ))}
          </div>
        </div>
      </section>

      <section id="stats" className="relative py-32 px-6 border-t border-white/5">
        <div className="mx-auto max-w-7xl reveal-group">
          <div className="reveal-item text-center max-w-2xl mx-auto mb-16 space-y-4">
            <span className="text-[#64ffda] text-xs font-bold tracking-[0.3em] uppercase">{tx("LIVE METRICS")}</span>
            <h2 className="text-4xl md:text-5xl font-bold tracking-tight">{tx("Measurable")} <span className="text-shimmer bg-gradient-to-r from-[#64ffda] to-[#00e699]">{tx("Results")}</span></h2>
            <p className="text-gray-400">{tx("Your real-time savings balance, powered by artificial intelligence.")}</p>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6 mb-12">
            {localizedStats.map((s: any, i: number) => (
              <TiltCard key={i} intensity={8} className="reveal-item relative group rounded-2xl border border-white/5 bg-gradient-to-br from-white/5 to-transparent p-6 hover:border-[#64ffda]/20 transition-all" style={{ transformStyle: "preserve-3d" }}>
                <div className="absolute inset-0 rounded-2xl opacity-0 group-hover:opacity-100 transition duration-500 pointer-events-none" style={{ background: s.glow, filter: "blur(30px)", transform: "translateZ(-10px)" }} />
                <div className="flex justify-between items-start" style={{ transform: "translateZ(45px)" }}>
                  <div className="w-10 h-10 rounded-xl bg-white/5 flex items-center justify-center" style={{ color: s.color }}><s.icon className="w-5 h-5" /></div>
                  <span className={`text-xs font-bold px-2 py-1 rounded-md ${s.pctUp ? 'bg-emerald-500/10 text-emerald-400' : 'bg-red-500/10 text-red-400'}`}>{s.pct}</span>
                </div>
                <div className="mt-6 space-y-1" style={{ transform: "translateZ(70px)" }}>
                  <h4 className="text-3xl font-black text-white"><CountUp value={s.value} /></h4>
                  <p className="text-sm font-bold text-gray-300">{s.label}</p>
                  <p className="text-[10px] text-gray-500">{s.desc}</p>
                </div>
              </TiltCard>
            ))}
          </div>
          <div className="reveal-item rounded-3xl border border-white/5 bg-gradient-to-b from-white/5 to-transparent p-6 md:p-10 backdrop-blur-md">
            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-6 mb-8">
              <div className="space-y-1">
                <h3 className="text-xl font-bold flex items-center gap-2"><Activity className="w-5 h-5 text-[#64ffda]" /> {tx("Annual Analytics Report")}</h3>
                <p className="text-xs text-gray-500">{tx("Real-time energy distribution for each month (kWh)")}</p>
              </div>
              <div className="flex bg-white/5 p-1.5 rounded-2xl border border-white/5 gap-2">
                <button onClick={() => setActiveTab("production")} className={`flex items-center gap-3 px-5 py-3 rounded-xl text-xs font-bold transition-all duration-300 ${activeTab === "production" ? "bg-[#10b981]/10 text-[#10b981] border border-[#10b981]/30 shadow-[0_0_15px_rgba(16,185,129,0.1)]" : "text-gray-400 hover:text-white hover:bg-white/5 border border-transparent"}`}>
                  <Sun className={`w-4 h-4 ${activeTab === "production" ? "text-[#fbbf24]" : "text-gray-500"}`} />
                  <div className="text-left"><span className="block leading-none">{tx("Energy Production")}</span><span className="text-[9px] text-gray-500 font-medium block mt-1">{tx("Generated by panels")}</span></div>
                </button>
                <button onClick={() => setActiveTab("consumption")} className={`flex items-center gap-3 px-5 py-3 rounded-xl text-xs font-bold transition-all duration-300 ${activeTab === "consumption" ? "bg-[#ef4444]/10 text-[#ef4444] border border-[#ef4444]/30 shadow-[0_0_15px_rgba(239,68,68,0.1)]" : "text-gray-400 hover:text-white hover:bg-white/5 border border-transparent"}`}>
                  <Zap className={`w-4 h-4 ${activeTab === "consumption" ? "text-[#ef4444]" : "text-gray-500"}`} />
                  <div className="text-left"><span className="block leading-none">{tx("Energy Consumption")}</span><span className="text-[9px] text-gray-500 font-medium block mt-1">{tx("Consumed by devices")}</span></div>
                </button>
              </div>
            </div>
            <div ref={chartRef} className="flex items-end h-64 gap-2 md:gap-4 border-b border-white/5 pb-2 relative">
              {chartData[activeTab].map((v: number, i: number) => (
                <div key={i} className="flex-1 flex flex-col items-center gap-2 group cursor-pointer h-full justify-end relative">
                  <div className="absolute bottom-full mb-3 px-3 py-1.5 text-[10px] rounded-lg glass-strong border border-white/10 opacity-0 group-hover:opacity-100 transition-all duration-300 pointer-events-none transform translate-y-2 group-hover:translate-y-0 z-20 whitespace-nowrap shadow-xl"><span className="font-extrabold text-white">{v * 6} kWh</span></div>
                  <div className="chart-bar w-full rounded-t-lg origin-bottom" style={{ height: `${v}%`, background: activeTab === "production" ? "linear-gradient(to top, #10b981, #64ffda)" : "linear-gradient(to top, #b91c1c, #ef4444)", boxShadow: activeTab === "production" ? "0 0 15px rgba(100, 255, 218, 0.15)" : "0 0 15px rgba(239, 68, 68, 0.15)" }} />
                  <span className="text-[10px] md:text-xs text-gray-500 font-semibold">{months[i]}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      <section id="how" className="relative py-24 px-4 border-t border-white/5 bg-black/10">
        <div className="mx-auto max-w-6xl reveal-group">
          <div className="reveal-item text-center max-w-2xl mx-auto mb-20 space-y-4">
            <span className="text-[#64ffda] text-xs font-bold tracking-[0.3em] uppercase">{tx("SIMPLE AND FAST")}</span>
            <h2 className="text-4xl md:text-5xl font-bold tracking-tight">{tx("Connect in Just 3 Steps")}</h2>
          </div>
          <div className="grid md:grid-cols-3 gap-10 relative">
            {localizedSteps.map((s: any, i: number) => (
              <TiltCard key={i} intensity={5} className="reveal-item relative rounded-3xl border border-white/5 bg-white/5 p-8 flex flex-col justify-between min-h-[300px]" style={{ transformStyle: "preserve-3d" }}>
                <div className="flex justify-between items-start" style={{ transform: "translateZ(40px)" }}>
                  <span className="text-5xl font-extrabold text-[#64ffda]/10">{s.n}</span>
                  <div className="w-10 h-10 rounded-xl bg-white/5 flex items-center justify-center text-[#64ffda]"><s.icon className="w-5 h-5" /></div>
                </div>
                <div className="space-y-2 mt-8" style={{ transform: "translateZ(60px)" }}>
                  <h4 className="text-xl font-bold text-white">{s.title}</h4>
                  <p className="text-sm text-gray-400 leading-relaxed">{s.desc}</p>
                </div>
              </TiltCard>
            ))}
          </div>
        </div>
      </section>

      <section id="contact" className="relative py-32 px-6 border-t border-white/5">
        <div className="mx-auto max-w-5xl reveal-group">
          <div className="rounded-[40px] border border-white/5 bg-gradient-to-br from-white/5 to-transparent p-10 md:p-16 relative overflow-hidden grid md:grid-cols-2 gap-12 items-center">
            <div className="absolute top-0 right-0 w-80 h-80 rounded-full bg-[#64ffda]/3 blur-[120px] -z-10" />
            <div className="reveal-item space-y-6">
              <span className="text-xs font-bold tracking-widest text-[#64ffda] uppercase">{tx("FREE ENERGY AUDIT")}</span>
              <h3 className="text-4xl font-bold leading-tight">{tx("Experience the Future of Energy Today")}</h3>
              <p className="text-gray-400 text-sm leading-relaxed">{tx("Start today and we will prepare a free savings simulation tailored to your home's current tariffs.")}</p>
              <ul className="space-y-4 pt-4 text-sm text-gray-300">
                <li className="flex items-center gap-3"><span className="w-5 h-5 rounded-full bg-[#64ffda]/10 flex items-center justify-center text-[#64ffda]"><Check className="w-3 h-3" /></span>{tx("14-day commitment-free trial")}</li>
                <li className="flex items-center gap-3"><span className="w-5 h-5 rounded-full bg-[#64ffda]/10 flex items-center justify-center text-[#64ffda]"><Check className="w-3 h-3" /></span>{tx("Live ROI report")}</li>
              </ul>
            </div>
            <form onSubmit={onSubmit} className="reveal-item space-y-4 backdrop-blur-md bg-black/20 border border-white/5 rounded-2xl p-6 md:p-8">
              <label className="block space-y-2"><span className="text-xs text-gray-400">{tx("Ad Soyad")}</span><input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder={tx("Your full name")} className="w-full px-4 py-3 rounded-xl bg-white/5 border border-white/10 focus:border-[#64ffda] outline-none transition duration-300 text-sm" /></label>
              <label className="block space-y-2"><span className="text-xs text-gray-400">{tx("E-mail")}</span><input type="email" required value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="example@ecoai.com" className="w-full px-4 py-3 rounded-xl bg-white/5 border border-white/10 focus:border-[#64ffda] outline-none transition duration-300 text-sm" /></label>
              <label className="block space-y-2"><span className="text-xs text-gray-400">{tx("Phone number")}</span><input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} placeholder="+994 (50) 000-0000" className="w-full px-4 py-3 rounded-xl bg-white/5 border border-white/10 focus:border-[#64ffda] outline-none transition duration-300 text-sm" /></label>
              <button type="submit" disabled={loading} className="w-full mt-4 py-4 rounded-xl bg-[#00e699] text-[#030d0a] font-bold hover:bg-[#00cc88] transition-all duration-300 flex items-center justify-center gap-2 disabled:opacity-50">
                {loading ? <><span className="w-5 h-5 border-2 border-[#030d0a] border-t-transparent rounded-full animate-spin" />{tx("Sending...")}</> : <>{tx("Get started")} <ArrowRight className="w-4 h-4" /></>}
              </button>
            </form>
          </div>
        </div>
      </section>

      <footer className="relative pt-20 pb-12 px-6 border-t border-white/5 bg-[#010604]">
        <div className="mx-auto max-w-7xl">
          <div className="grid gap-12 md:grid-cols-12 mb-16">
            <div className="md:col-span-4 space-y-4">
              <Logo />
              <p className="text-sm text-gray-500 max-w-xs">{tx("An AI-powered platform for green energy optimization.")}</p>
              <div className="flex gap-3 pt-2">
                {[
                  { Icon: Linkedin, href: "https://www.linkedin.com/in/omar-babayev-21888437b" },
                  { Icon: Github, href: "https://github.com/etikhacker" },
                  { Icon: Mail, href: "mailto:babayev.omr.23@gmail.com" },
                  { Icon: Send, href: "https://t.me/EduTrackAssistantBot" },
                  { Icon: Facebook, href: "https://www.facebook.com/share/1BWb7iSsQ9/"}
                ].map(({ Icon, href }, i) => (
                  <a key={i} href={href} target="_blank" rel="noopener noreferrer" className="w-10 h-10 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center hover:bg-[#64ffda]/10 hover:border-[#64ffda]/30 transition duration-300"><Icon className="w-4 h-4 text-[#64ffda]" /></a>
                ))}
              </div>
            </div>
            <div className="md:col-span-8 grid grid-cols-2 md:grid-cols-4 gap-8">
              {localizedFooter.map((c: any, i: number) => (
                <div key={i}>
                  <h4 className="text-sm font-bold text-white mb-4">{c.title}</h4>
                  <ul className="space-y-2 text-sm text-gray-500">
                    {c.links.map((l: string, j: number) => (
                      <li key={j}><a href="#" className="hover:text-[#64ffda] transition duration-300">{l}</a></li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </div>
          <div className="pt-8 border-t border-white/5 flex flex-col sm:flex-row items-center justify-between gap-4 text-xs text-gray-600">
            <p>© 2026 EcoAI. {tx("All rights reserved.")}</p>
            <p>{tx("Made with ⚡ in Baku")}</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
